SELECT M.TITLE, SUM(S.CHARGE) AS PROFIT FROM MOVIE M, STREAM S, MOVIE_GENRE MG, GENRE G WHERE M.MOVIEID = MG.MOVIEID AND G.GENREID = MG.GENREID AND G.LABEL = 'Action' AND S.MOVIEID = M.MOVIEID GROUP BY M.TITLE ORDER BY PROFIT DESC, M.TITLE ASC LIMIT 20;

