UPDATE STREAM AS S INNER JOIN MOVIE AS M ON S.MOVIEID = M.MOVIEID INNER JOIN CUSTOMER AS C ON S.CUSTOMERID = C.CUSTOMERID INNER JOIN COUNTRY AS CO ON C.COUNTRY = CO.NAME INNER JOIN REGION AS R ON CO.REGIONID = R.REGIONID SET S.CHARGE = S.CHARGE + 1.5 WHERE M.DURATION >= 180 AND R.NAME = 'Europe';

