SELECT R.NAME AS REGIAO, G.LABEL AS GENERO, SUM(S.CHARGE) AS VALOR, SUM(M.DURATION) AS TEMPO FROM STREAM S, CUSTOMER C, COUNTRY CO, GENRE G, MOVIE_GENRE MG, MOVIE M, REGION R WHERE S.CUSTOMERID = C.CUSTOMERID AND C.COUNTRY = CO.NAME AND CO.REGIONID  = R.REGIONID AND S.MOVIEID = MG.MOVIEID AND MG.GENREID = G.GENREID AND S.MOVIEID = M.MOVIEID GROUP BY REGIAO, GENERO ORDER BY REGIAO, GENERO;

